// <auto-generated />
using System;
using Arko.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arko.API.Migrations
{
    [DbContext(typeof(ArkoDbContext))]
    partial class ArkoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arko.Core.Models.Analyst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Analistas", (string)null);
                });

            modelBuilder.Entity("Arko.Core.Models.CurrentStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique();

                    b.ToTable("EstoqueAtual", (string)null);
                });

            modelBuilder.Entity("Arko.Core.Models.Discharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDischarge")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique();

                    b.ToTable("Baixa", (string)null);
                });

            modelBuilder.Entity("Arko.Core.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnalyst")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipment")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("IdAnalyst");

                    b.HasIndex("IdEquipment");

                    b.ToTable("Entradas", (string)null);
                });

            modelBuilder.Entity("Arko.Core.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Equipamentos", (string)null);
                });

            modelBuilder.Entity("Arko.Core.Models.Exit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnalyst")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAnalyst");

                    b.HasIndex("IdEquipment");

                    b.ToTable("Saidas", (string)null);
                });

            modelBuilder.Entity("Arko.Core.Models.CurrentStock", b =>
                {
                    b.HasOne("Arko.Core.Models.Equipment", "Equipment")
                        .WithOne("CurrentStock")
                        .HasForeignKey("Arko.Core.Models.CurrentStock", "EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Arko.Core.Models.Discharge", b =>
                {
                    b.HasOne("Arko.Core.Models.Equipment", "Equipment")
                        .WithOne("Discharge")
                        .HasForeignKey("Arko.Core.Models.Discharge", "EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Arko.Core.Models.Entry", b =>
                {
                    b.HasOne("Arko.Core.Models.Analyst", "Responsible")
                        .WithMany("Entries")
                        .HasForeignKey("IdAnalyst")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arko.Core.Models.Equipment", "Equipment")
                        .WithMany("Entries")
                        .HasForeignKey("IdEquipment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Arko.Core.Models.Exit", b =>
                {
                    b.HasOne("Arko.Core.Models.Analyst", "Responsible")
                        .WithMany("Exits")
                        .HasForeignKey("IdAnalyst")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arko.Core.Models.Equipment", "Equipment")
                        .WithMany("Exits")
                        .HasForeignKey("IdEquipment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Arko.Core.Models.Analyst", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Exits");
                });

            modelBuilder.Entity("Arko.Core.Models.Equipment", b =>
                {
                    b.Navigation("CurrentStock");

                    b.Navigation("Discharge");

                    b.Navigation("Entries");

                    b.Navigation("Exits");
                });
#pragma warning restore 612, 618
        }
    }
}
